name: Deployment_exe_2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: install_dependencies
        run: npm ci
      - name: lint_job
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: get_code
        uses: actions/checkout@v3
      - name: install_dependencies
        run: npm ci
      - name: test_job
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: install_dependencies
        run: npm ci
      - name: build_code
        run: npm run build
      - name: deploy_job
        run: echo "Deploying ...."